development:
  adapter: postgresql
  host: ec2-23-21-219-12.compute-1.amazonaws.com
  username: wesbolsiwhtbkt
  database: d1p3fupc8dm0mb
  password: 3lI6Z_EZFttcKVGaREmNEaFDCF
  
test:
  adapter: postgresql
  host: ec2-54-221-226-148.compute-1.amazonaws.com
  username: msvrcdoktojtmi
  database: d261m2ri8p855a
  password: y_suwaVAZI5lsSfhVuR4aqJjj5
