default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: wesbolsiwhtbkt
  password: 3lI6Z_EZFttcKVGaREmNEaFDCF

development:
  <<: *default
  database: catarse_development

test:
  <<: *default
  database: catarse_test
