default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: password

development:
  <<: *default
  database: catarse_development

test:
  <<: *default
  database: catarse_test
